export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';
export const REQUEST_DATA = 'REQUEST_DATA';
export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const CHANGE_DATE = "CHANGE_DATE";
export const NEW_SORT = "NEW_SORT";
export const OLD_SORT = "OLD_SORT";
export const FILTER_PRODUCT = "FILTER_PRODUCT";